# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\aperturewindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ApertureWindow(object):
    def setupUi(self, ApertureWindow):
        ApertureWindow.setObjectName("ApertureWindow")
        ApertureWindow.resize(400, 300)
        ApertureWindow.setAutoFillBackground(False)
        self.formLayout = QtWidgets.QFormLayout(ApertureWindow)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(ApertureWindow)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.major_axis = QtWidgets.QDoubleSpinBox(ApertureWindow)
        self.major_axis.setMaximum(100000000000000.0)
        self.major_axis.setProperty("value", 50.0)
        self.major_axis.setObjectName("major_axis")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.major_axis)
        self.label_2 = QtWidgets.QLabel(ApertureWindow)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.minor_axis = QtWidgets.QDoubleSpinBox(ApertureWindow)
        self.minor_axis.setMaximum(100000000000000.0)
        self.minor_axis.setProperty("value", 50.0)
        self.minor_axis.setObjectName("minor_axis")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.minor_axis)
        self.label_3 = QtWidgets.QLabel(ApertureWindow)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.angle = QtWidgets.QDoubleSpinBox(ApertureWindow)
        self.angle.setMaximum(100000000000000.0)
        self.angle.setObjectName("angle")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.angle)
        self.label_4 = QtWidgets.QLabel(ApertureWindow)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.gap = QtWidgets.QDoubleSpinBox(ApertureWindow)
        self.gap.setMaximum(100000000000000.0)
        self.gap.setProperty("value", 20.0)
        self.gap.setObjectName("gap")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.gap)
        self.label_5 = QtWidgets.QLabel(ApertureWindow)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.background = QtWidgets.QDoubleSpinBox(ApertureWindow)
        self.background.setProperty("showGroupSeparator", False)
        self.background.setMaximum(100000000000000.0)
        self.background.setProperty("value", 30.0)
        self.background.setObjectName("background")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.background)

        self.retranslateUi(ApertureWindow)
        QtCore.QMetaObject.connectSlotsByName(ApertureWindow)

    def retranslateUi(self, ApertureWindow):
        _translate = QtCore.QCoreApplication.translate
        ApertureWindow.setWindowTitle(_translate("ApertureWindow", "Aperture"))
        self.label.setText(_translate("ApertureWindow", "Major Axis"))
        self.label_2.setText(_translate("ApertureWindow", "Minor Axis"))
        self.label_3.setText(_translate("ApertureWindow", "Angle"))
        self.label_4.setText(_translate("ApertureWindow", "Gap"))
        self.label_5.setText(_translate("ApertureWindow", "Background"))
