# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\graphwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GraphWindow(object):
    def setupUi(self, GraphWindow):
        GraphWindow.setObjectName("GraphWindow")
        GraphWindow.resize(400, 300)
        GraphWindow.setAutoFillBackground(False)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(GraphWindow)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.graph = QtWidgets.QOpenGLWidget(GraphWindow)
        self.graph.setObjectName("graph")
        self.verticalLayout_2.addWidget(self.graph)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.comboBox = QtWidgets.QComboBox(GraphWindow)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout.addWidget(self.comboBox)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(GraphWindow)
        QtCore.QMetaObject.connectSlotsByName(GraphWindow)

    def retranslateUi(self, GraphWindow):
        _translate = QtCore.QCoreApplication.translate
        GraphWindow.setWindowTitle(_translate("GraphWindow", "Graph Window"))
        self.comboBox.setItemText(0, _translate("GraphWindow", "None"))
        self.comboBox.setItemText(1, _translate("GraphWindow", "Line"))
        self.comboBox.setItemText(2, _translate("GraphWindow", "Horizontal Box"))
        self.comboBox.setItemText(3, _translate("GraphWindow", "Area"))
