# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\objectswindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ObjectsWindow(object):
    def setupUi(self, ObjectsWindow):
        ObjectsWindow.setObjectName("ObjectsWindow")
        ObjectsWindow.resize(450, 438)
        self.verticalLayout = QtWidgets.QVBoxLayout(ObjectsWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.objects_table = QtWidgets.QTableWidget(ObjectsWindow)
        self.objects_table.setObjectName("objects_table")
        self.objects_table.setColumnCount(0)
        self.objects_table.setRowCount(0)
        self.verticalLayout.addWidget(self.objects_table)
        self.export_button = QtWidgets.QPushButton(ObjectsWindow)
        self.export_button.setObjectName("export_button")
        self.verticalLayout.addWidget(self.export_button)

        self.retranslateUi(ObjectsWindow)
        QtCore.QMetaObject.connectSlotsByName(ObjectsWindow)

    def retranslateUi(self, ObjectsWindow):
        _translate = QtCore.QCoreApplication.translate
        ObjectsWindow.setWindowTitle(_translate("ObjectsWindow", "Form"))
        self.export_button.setText(_translate("ObjectsWindow", "Export"))
